### POST SIGNIN 
POST http://localhost:8000/api/signin
Content-Type: application/json

{
    "email": "abcd@mail.com",
    "password": "abcdpassword"
}

### POST SIGNUP
POST http://localhost:8000/api/signup
Content-Type: application/json

{
    "firstname": "abcd",
    "lastname": "abcd",
    "street": "abcd",
    "city": "abcd",
    "postal_code": "2",
    "email": "abcd@mail.com",
    "password": "abcdpassword",
    "phone_number": "xxx",
    "role": "user"
}