### GET ALL CATEGORIES
GET http://localhost:8000/api/categories

### GET A CATEGORY
GET http://localhost:8000/api/categories/1

### POST A CATEGORY
POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "Rocher"
}

### PUT
PUT http://localhost:8000/api/categories/1
Content-Type: application/json

{
    "name": "Tablette de chocolat"
}

###DELETE
DELETE http://localhost:8000/api/categories/1